"""initial migration

Revision ID: 3e8cd0c9004d
Revises: 1928dc6a6de8
Create Date: 2025-06-15 18:21:50.370711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8cd0c9004d'
down_revision = '1928dc6a6de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('comment', sa.VARCHAR(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_reviews_customer_id_customers'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='fk_reviews_item_id_items'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
